---


 - name: Ensure that the keystone package is installed
   apt: pkg=keystone state=installed

 - name: Ensure that the package python-openstackclient is installed
   apt: pkg=python-openstackclient state=installed

 - name: Ensure that the package apache2 is installed
   apt: pkg=apache2 state=installed

 - name: Ensure that the package libapache2-mod-wsgi is installed
   apt: pkg=libapache2-mod-wsgi state=installed

 - name: Ensure that the package memcached is installed
   apt: pkg=memcached state=installed

 - name: Ensure that the package python-memcache is installed
   apt: pkg=python-memcache state=installed

 - name: Ensure that the package curl is installed
   apt: pkg=curl state=installed

 - name: Prevent keystone from starting while apache is being configured
   shell: echo "manual" > /etc/init/keystone.override

 - name: Install the templated keystone.conf file
   template: src=keystone.conf dest=/etc/keystone/keystone.conf

 - name: Install the templated apache2.conf file
   template: src=apache2.conf dest=/etc/apache2/apache2.conf

 - name: Install the templated wsgi-keystone.conf file
   template: src=wsgi-keystone.conf dest=/etc/apache2/sites-available/wsgi-keystone.conf

 - name: Populate the identity service database
   shell: su -s /bin/sh -c "keystone-manage db_sync" keystone

 - name: Disbaling the default apache2 virtual host
   shell: rm -f /etc/apache2/sites-enabled/000-default.conf 2>/dev/null

 - name: Enable the identity service virtual host
   shell: ln -sf /etc/apache2/sites-available/wsgi-keystone.conf /etc/apache2/sites-enabled

 - name: Make the directory structure for the WSGI components
   shell: mkdir -p /var/www/cgi-bin/keystone

 - name: Download the WSGI components from upstream
   shell: curl http://git.openstack.org/cgit/openstack/keystone/plain/httpd/keystone.py?h=stable/kilo | tee /var/www/cgi-bin/keystone/main /var/www/cgi-bin/keystone/admin

 - name: Adjusting permissions of WSGI directory
   shell: chown -R keystone:keystone /var/www/cgi-bin/keystone; chmod 755 /var/www/cgi-bin/keystone/*

 - name: Remove the sqlite database
   shell: rm -f /var/lib/keystone/keystone.db

 - name: Stop the apache2 service
   shell: service apache2 stop

 - name: Stop the keystone service
   shell: service keystone stop; sleep 1

 - name: Restart the apache2 service
   shell: service apache2 start

# - name: Start the keystone service
#   shell: service keystone start

 - include: create-keystone-users.yml
