---

 - name: Ensure lvm2 is installed
   apt: pkg=lvm2 state=installed
   when: inventory_hostname == openstack_ctl_master or inventory_hostname == openstack_ctl_slave

 - name: Prepare the VG and LVS for mysql and rabbit for use by drbd
   script: config-ha-lvs.sh 
   failed_when: 6 == 9
   when: inventory_hostname == openstack_ctl_master or inventory_hostname == openstack_ctl_slave
