---

# pacemaker (Note that the crm shell should be downloaded separately.)

 - name: Installed required packages for pacemaker
   apt: pkg={{ item }} state=installed
   with_items:
   - pacemaker
   - crmsh
   - corosync
   - cluster-glue
   - resource-agents
   - libvotequorum6

 - name: Copy the templated corosysc.conf file
   template: src=corosync.j2 dest={{ item }}/corosync.conf mode=644 owner=root group=root
   with_items:
   - /etc/default
   - /etc/corosync

 - name: Configure corosync to auto load on boot
   shell: echo "START=yes" > /etc/default/corosync

 - name: Ensure logging directory exists
   shell: mkdir -p /var/log/cluster/

 - name: Restart the corosync service
   service: name={{ item }} state=restarted
   with_items:
   - corosync
   - pacemaker

