---

# pacemaker (Note that the crm shell should be downloaded separately.)

 - name: Installed required packages for pacemaker
   apt: pkg={{ item }} state=installed
   with_items:
   - pacemaker
   - crmsh
   - corosync
   - cluster-glue
   - resource-agents
   - crmsh
   - libvotequorum6

 - name: Copy the templated corosysc.conf file
   template: src=corosync.j2 dest=/etc/corosync/corosync.conf mode=644 owner=root group=root
