---

# pacemaker (Note that the crm shell should be downloaded separately.)

 - name: Installed required packages for pacemaker
   apt: pkg={{ item }} state=installed
   with_items:
   - pacemaker
   - crmsh
   - corosync
   - cluster-glue
   - resource-agents
