---

- include: common-pre-actions.yml
- include: database.yml
- include: high-availability.yml
- include: keystone.yml
- include: glance.yml
- include: nova-cpu.yml
- include: nova-ctl.yml
- include: neutron-net.yml
- include: neutron-cpu.yml
- include: neutron-ctl.yml
- include: neutron-initial-net.yml
- include: horizon.yml
- include: cinder-storage.yml
- include: cinder-ctl.yml
- include: heat.yml
- include: swift-ctl.yml
- include: ceilometer-ctl.yml
- include: designate.yml
- include: swift-storage.yml
