---

- hosts: openstack-ctl-master-node

  sudo: yes

  vars:
    image_path: /var/lib/glance/images/
    cirros_path: https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img
    cirros_image_name: cirros-0.3.0-x86_64

    trusty_path: "http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img"
    trusty_image_name: "trusty-server-cloudimg-amd64"

    env:
      OS_PROJECT_DOMAIN_ID: "default"
      OS_USER_DOMAIN_ID: "default"
      OS_PROJECT_NAME: "admin"
      OS_TENANT_NAME: "admin"
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ keystone_admin_pass }}"
      OS_AUTH_URL: "http://{{ openstack_ctl_master }}:35357/v3"
      OS_IMAGE_API_VERSION: "2"

  roles:

    - glance

