---

- hosts: openstack-all-nodes

  gather_facts: True

  sudo: yes

  vars:

    net_man_gw: 192.168.10.1
    net_man_pre: 192.168.10.
    net_stg_pre: 192.168.20.
    net_tun_pre: 192.168.30.
    net_common_mask: 255.255.255.0
    net_dhcp_dev: eth0

    env:
      NET_DHCP_DEV: "{{ net_dhcp_dev }}"

      NET_MAN_DEV: "{{ net_man_dev }}"
      NET_STG_DEV: "{{ net_stg_dev }}"
      NET_TUN_DEV: "{{ net_tun_dev }}"
      NET_EXT_DEV: "{{ net_ext_dev }}"

      NET_MAN_GW: "{{ net_man_gw }}"
      NET_MAN_PRE: "{{ net_man_pre }}"
      NET_STG_PRE: "{{ net_stg_pre }}"
      NET_TUN_PRE: "{{ net_tun_pre }}"
      NET_COMMON_MASK: "{{ net_common_mask }}"

  roles:

    - network-setup

