---

- hosts: openstack-ctl-master-node

  sudo: yes

  vars:  
    external_net_cidr: "10.2.134.0/24"
    floating_ip_start: "10.2.134.1"
    floating_ip_end: "10.2.134.240"
    external_net_gw: "10.2.134.254"
    tenant_net_cidr: "192.168.50.0/24"
    tenant_net_gw: "192.168.50.1"
  
    env:
      OS_PROJECT_DOMAIN_ID: "default"
      OS_USER_DOMAIN_ID: "default"
      OS_PROJECT_NAME: "admin"
      OS_TENANT_NAME: "admin"
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ keystone_admin_pass }}"
      OS_AUTH_URL: "http://{{ openstack_ctl_master }}:35357/v3"
      OS_IMAGE_API_VERSION: "2"

    demo:
      OS_PROJECT_DOMAIN_ID: "default"
      OS_USER_DOMAIN_ID: "default"
      OS_PROJECT_NAME: "demo"
      OS_TENANT_NAME: "demo"
      OS_USERNAME: "demo"
      OS_PASSWORD: "{{ keystone_demo_pass }}"
      OS_AUTH_URL: "http://{{ openstack_ctl_master }}:5000/v3"
      OS_IMAGE_API_VERSION: "2"

  roles:

    - neutron-initial-net

